#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=00


TUNDRA_EXECUTABLE="/usr/local/sbin/tundra-nat64"
TUNDRA_CONFIG_FILE="/etc/tundra-nat64/tundra-nat64.conf"

TUNDRA_INTERFACE_NAME="tundra"
TUNDRA_INTERFACE_IPV4="10.64.64.254/24"
TUNDRA_INTERFACE_IPV6="fd64:6464::fffe/64"
TUNDRA_TRANSLATION_PREFIX="64:ff9b::/96"


start_service() {
    $TUNDRA_EXECUTABLE --config-file=$TUNDRA_CONFIG_FILE mktun || return 1
    /sbin/ip link set dev $TUNDRA_INTERFACE_NAME up || return 1
    /sbin/ip addr add $TUNDRA_INTERFACE_IPV4 dev $TUNDRA_INTERFACE_NAME || return 1
    /sbin/ip -6 addr add $TUNDRA_INTERFACE_IPV6 dev $TUNDRA_INTERFACE_NAME || return 1
    /sbin/ip -6 route add $TUNDRA_TRANSLATION_PREFIX dev $TUNDRA_INTERFACE_NAME || return 1

    procd_open_instance
    procd_set_param command $TUNDRA_EXECUTABLE --config-file=$TUNDRA_CONFIG_FILE translate
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param term_timeout 15
    procd_close_instance
}

service_stopped() {
    /bin/sleep 2 || return 1

    $TUNDRA_EXECUTABLE --config-file=$TUNDRA_CONFIG_FILE rmtun || return 1
}
